services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-aerodb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spring-service:
    build: ./spring-service
    container_name: spring-service
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - PREPROCESS_SERVICE_URL=${PREPROCESS_SERVICE_URL}
      - INFERENCE_SERVICE_URL=${INFERENCE_SERVICE_URL}
      - PORT=${SPRING_PORT:-8087}
    ports:
      - "${SPRING_PORT:-8087}:8080"
    depends_on:
      - postgres
      - minio

  preprocess-service:
    build: ./preprocess-service
    container_name: preprocess-service
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_RAW=bucket-raw
      - MINIO_BUCKET_PROCESSED=bucket-processed
      - MINIO_BUCKET_RESULTS=bucket-results
      - PORT=${PREPROCESS_PORT:-8001}
    ports:
      - "${PREPROCESS_PORT:-8001}:8001"

  inference-service:
    build: ./inference-service
    container_name: inference-service
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_RAW=bucket-raw
      - MINIO_BUCKET_PROCESSED=bucket-processed
      - MINIO_BUCKET_RESULTS=bucket-results
      - PORT=${INFERENCE_PORT:-8002}
    ports:
      - "${INFERENCE_PORT:-8002}:8002"
  frontend:
      build:
        context: ./frontend
      ports:
        - "${FRONTEND_PORT:-8088}:80"
      depends_on:
        - spring-service

volumes:
  pgdata:
  minio_data:
