name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 60m
          script: |
            set -e
            cd /srv/aeroresnet/toolspredict

            export GIT_SSH_COMMAND='ssh -i ~/.ssh/github_deploy -o StrictHostKeyChecking=no'

            git fetch origin develop
            git reset --hard origin/develop

            echo "Building and restarting all services..."
            docker compose build
            docker compose up -d